# Site settings
title: Jeni's Musings
email: jeni@jenitennison.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Jeni Tennison
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jenitennison.com" # the base hostname & protocol for your site
twitter_username: jenit
github_username:  jenit
paginate: 5
paginate_path: "archive/:num/"
excerpt_separator: "<!--break-->"

# Build settings
markdown: kramdown