# Site settings
title: Jeni Tennison
email: jeni@jenitennison.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Jeni Tennison
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jenitennison.com" # the base hostname & protocol for your site
twitter_username: jenit
github_username:  jenit
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "archive/:num/"

# Build settings
markdown: kramdown
